### ISSUE TITLE
Set default country to none

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#1]
See the following - https://skitch.com/gusaus/ef7a5/configure-site-drupal

**Comment by discipolo** [comment]
looks like it uses the users timezone (taken from browser?) but the codes default country. cause for me it uses my timezone on install

**Comment by discipolo** [comment]
is there a way to set defaultcountry to "none"? whats the proper action to take here?

**Comment by gusaus** [comment]
marking as resolved

**Comment by gusaus** [comment]
For some reason, the default country is again set to Austria with the latest push.

**Comment by discipolo** [comment]
should be fixed with https://github.com/Pushtape/pushtape/commit/e091163c90d8ddead2b5f7fc05063bb2dd43712b

**Comment by gusaus** [comment]
yes!
