### ISSUE TITLE
 Notice: Undefined index: last-modified in apps_retrieve_app_image() (line 259...

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#10]
Also still getting these errors upon install - 

Notice: Undefined index: last-modified in apps_retrieve_app_image() (line 259 of /srv/bindings/e36386497bcb4dbb9dca27120a534b6f/code/profiles/pushtape/modules/contrib/apps/apps.manifest.inc).

A similar issue is logged here - someone else got the error - http://drupal.org/node/1763394

**Comment by gusaus** [comment]
Looks like a fix is in the works..... http://drupal.org/node/1763394#comment-6431144

**Comment by discipolo** [comment]
this is none of our concern
