### ISSUE TITLE
Set flux as default theme

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#12]
Can we set flux as the default theme upon install?

**Comment by discipolo** [comment]
flux is meant as admin theme. we still need to figure out how to provide goodlooking flavours for the actual frontend

**Comment by gusaus** [comment]
I'm pretty sure Flux is intended to be the default theme. Not just admin.... http://drupal.org/project/flux

**Comment by discipolo** [comment]
alright. if that is the consensus i defer. Flux now is default theme.

**Comment by discipolo** [comment]
since the theme chooser on install moved into panopoly_theme i dont know why the default from our.install file isnt picked up

which means i cannot fix this and have to defer for now

**Comment by gusaus** [comment]
We need more info/clarity from the Panopoly folks?

**Comment by discipolo** [comment]
yes, we need to figure out how to make panopoly_theme.profile.inc line 42 check whether the variable 'theme_default' has been set in our distros pushtape.install file and use that as default value. or any other way to override this default on install
 panopoly_theme hardcodes the default value to be responsive_bartik it should respect the value we assigned to  'theme_default' if that is possible. If not there must be a way for us to override in our distros .profile file ask in panopoly_theme issuequeue maybe

**Comment by gusaus** [comment]
Still need to followup w/ panopoly

**Comment by discipolo** [comment]
http://drupal.org/node/1854542#comment-6795784

https://github.com/Pushtape/pushtape/commit/49f3c749bf88767e9a13e7fe0f038e0a54260eda

committed, please test

**Comment by gusaus** [comment]
Looks like you noticed also that it still does not work - http://drupal.org/node/1854542#comment-6798064

Thanks for posting

**Comment by gusaus** [comment]
Does this give you an idea of what we're still doing wrong? http://drupal.org/node/1854542#comment-6814336

**Comment by discipolo** [comment]
Posted by populist on December 5, 2012 at 7:56pm new
Status: active  » fixed

The solution here should just be to implement different logic in your .profile file. The code in panopoly_theme.profile.inc will bring in a theme selection form, but you don't need to pull that in or you can implement a hook_FORMID_form_alter() in your .profile to change the default.

**Comment by gusaus** [comment]
the changes worked this time!! closing this down

thanks discipolo!
