### ISSUE TITLE
Push latest code on d.o. upstream

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#13]
Per our discussion we need to have the latest dev code sent upstream from d.o. to panels branch.

**Comment by discipolo** [comment]
there are no changes beyond adding the theme and updating views on d.o none of those apply to panels (they do apply to upstream though.

**Comment by gusaus** [comment]
There are also some 'minor changes' like to the help text. Its confusing if those changes are not in this branch. Do you want me to just manually make the changes so they're identical?
