### ISSUE TITLE
Enable panopoly apps upon install

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#14]
Not sure what changed, but it looks like (most) of the Panopoly apps need to be set to enable during install - https://skitch.com/gusaus/et3cy/install-apps-pushtape-panels

right?

**Comment by discipolo** [comment]
panopoly apps should be active on install. is this issue still reproducable? if not please close.

**Comment by gusaus** [comment]
Panopoly apps are now enabled. However, for some reason Pushtape apps also appear on the same page - https://skitch.com/gusaus/e1wej/install-apps-pushtape-panels

**Comment by gusaus** [comment]
Pushtape apps 'DO' still appear on the next install screen. Only pushtape_ui is enabled tho... https://skitch.com/gusaus/e1wku/install-apps-pushtape-panels

**Comment by discipolo** [comment]
please make this a new issue. original issue is resolved

**Comment by gusaus** [comment]
ok
