### ISSUE TITLE
Pushtape apps have dissapeared 

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#16]
Not sure what happened, but you can no longer access/install Pushtape apps after install - 

https://skitch.com/gusaus/e1e27/pushtape-panels
http://dev.pushtape-panels.gotpantheon.com/admin/apps/pushtape

**Comment by discipolo** [comment]
moved appserver connectort into pushtape_ui. issue should be resolved

**Comment by gusaus** [comment]
The apps have reappeared! I did come across this message that might relate to the new fix? 

https://skitch.com/gusaus/e1qd5/performance-pushtape-panels

Notice: Undefined variable: profile in pushtape_ui_apps_servers_info() (line 24 of /srv/bindings/e36386497bcb4dbb9dca27120a534b6f/code/profiles/pushtape/modules/pushtape_apps/pushtape_ui/pushtape_ui.module).

**Comment by discipolo** [comment]
that should not appear anymore.
