### ISSUE TITLE
Clean up Pushtape and Panopoly apps install

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#19]
Currently upon install we have 2 'Install Apps' screens - 

1) Panopoly and Pushtape apps combined - Panopoly apps are (properly) enabled. Pushtape apps also appear on the same page - https://skitch.com/gusaus/e1wej/install-apps-pushtape-panels
2) Pushtape apps - https://skitch.com/gusaus/e1wku/install-apps-pushtape-panels

This will be confusing to both users and site admins alike. 

My suggestion, if at all possible, would be to 1) hide the entire Panopoly install screen (but still have the apps enable by default); 2) replace Pushtape News with Panopoly News and just have the one App Install screen.

Is that possible?

**Comment by gusaus** [comment]
Would it be possible to change the App title/descriptions to something more generic - In other words remove the Pushtape or Panopoly names and just show something like - 
- Gallery
- Events
- News
- Discography 
  ....

**Comment by gusaus** [comment]
I did another install with all the panopoly apps except for panopoly core disabled. This time the install did not freeze and all the panopoly apps (except for wysiwyg) were enabled. Possibly you're making progress with what I suggested above?!?

**Comment by gusaus** [comment]
Looks like the dup apps screen has been resolved. Would still be great to make the app names displayed per my comment above - 
https://github.com/Pushtape/pushtape/issues/19#issuecomment-8636965

**Comment by gusaus** [comment]
Looks much, much better - a few notes - https://skitch.com/gusaus/eim6f/install-apps-pushtape-panels

@discipolo Feel free to close this down if you think this is resolved.

**Comment by discipolo** [comment]
closing this. 

FYI: here is an issue related to your other comment: https://github.com/Pushtape/pushtape/issues/23
