### ISSUE TITLE
Still having trouble with makefile

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#20]
I pushed a few minor changes but I'm running into errors again w/ the makefile - here is the output:

http://pastebin.com/pP26CPrD

Can you help troubleshoot and fix?

thank you!

**Comment by discipolo** [comment]
need more info

**Comment by gusaus** [comment]
My errors are different everytime - I'll blame my crappy computer. That said, we should make sure the makefile runs for others like pyrello.

**Comment by discipolo** [comment]
currently there actually is a nonexistant patch referenced somewhere ...

http://drupal.org/files/1605284-define-types-for-tokens.patch

**Comment by gusaus** [comment]
Yes - that looks like the same (and only) error I got during my latest attempt - 
http://pastebin.com/efeVC2ff (line 208)

Any idea where it came from and/or how to resolve?

**Comment by discipolo** [comment]
http://drupal.org/node/1797726
for the time beeing i am rebuilding using the --force-complete flag on drush make

**Comment by gusaus** [comment]
Nice one! It looks like that the patch issue was resolved and amazingly I was able to run the makefile and rebuild!

**Comment by gusaus** [comment]
I think this merge https://github.com/Pushtape/pushtape/pull/29 again broke the makefile. The one error I got was 'Unable to patch panelizer with panelizer-duplicates-1412022-18.patch.'

**Comment by discipolo** [comment]
it looks like our makefiles are downloading wrong versions of contrib which is why that patch doesnt apply. i went ahead and [specified the right version in pushtape discography](https://github.com/discipolo/pushtape_discography/commit/36c50709365c7e245300d9e8d37b0f0c0c918f47). that should take care of things. now its another issue to update those contrib versions specifications whenever panopoly_core does so.

**Comment by gusaus** [comment]
Its worked the last several times I've tried to run it - closing this down again!

**Comment by gusaus** [comment]
I'm unable to run the makefile again. Last several attempts have been unsuccessful. Any ideas on what may be causing this?

**Comment by gusaus** [comment]
Looks like the error is - Unable to patch media with media-file-view-mode-1051090-56.patch.    [error]

So that patch needs to be removed from mediaplayer.make

**Comment by gusaus** [comment]
Per @discipolo's advice I removed the patch from the makefile - https://github.com/Pushtape/pushtape_mediaplayer/commit/e3d9dbe9cc38c2a8c6979c0fc3c09ba20562b35a

Working again!

**Comment by gusaus** [comment]
Tried to run the makefile again (first time in a couple weeks) and it's broken again. Looking over the recent history, I'm thinking some of the commits might be the culprit?

https://github.com/Pushtape/pushtape/commit/39fb94a37889d870c0bd9237d7486adf571a0760
https://github.com/Pushtape/pushtape/commit/4f843a7aa8214eb145baeb747fe5b72740346aa0
https://github.com/Pushtape/pushtape/commit/e633ce871c47ee68a875f42aa7fb89c033a435d8
https://github.com/Pushtape/pushtape/commit/628131b16fc1d2f4aa31b75e0be68736f5555561
https://github.com/Pushtape/pushtape/commit/679eeed1a9937169259721940cb5fc858d16f80b

Not sure what the goal was here, but we shouldn't be mixing in spark stuff.

**Comment by discipolo** [comment]
drush make https://raw.github.com/Pushtape/pushtape/7.x-1.x-panels/build-pushtape.make works just fine. those commits are on a different branch
