### ISSUE TITLE
Add back pushtape news

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#23]

**Comment by gusaus** [comment]
Per our discussion we will be adding back https://github.com/Pushtape/pushtape_news - would be great if we could add that back soon!

**Comment by discipolo** [comment]
stuff we will build on instead of duplicate includes panopoly_news. http://drupal.org/node/1704270

but we can work on the way we implement it. i proposed trying to rebrand it to avoid confusion at a later point. the key here is that we have a working news app which is maintained by the panopoly people (and us).

i do see your issue with it being called differently. so renaming this issue accordingly.

**Comment by gusaus** [comment]
The Pushtape news app worked fine and is more consistent with the other add-on apps (such as events). It also uses the pushtape_news namespace and resides on our appserver. I understand the benefits of leveraging the latest/greatest panopoly functionally, but we can still do that with the feature we already have. Please lets just add the old app back.

**Comment by discipolo** [comment]
lets try this https://github.com/Pushtape/pushtape/issues/19#issuecomment-8636965 i like that best.

**Comment by discipolo** [comment]
please make an issue http://drupal.org/project/issues/panopoly_news or add to the somewhat related http://drupal.org/node/1444770

**Comment by gusaus** [comment]
Please set up a new issue instead of completely rewriting this issue. It is not relevant to the need for adding 'Pushtape News' back to this branch. Thank you

**Comment by discipolo** [comment]
http://drupal.org/node/1444770

**Comment by gusaus** [comment]
The issue you're referencing just validates the fact there's no solution yet for what your looking for. As I noted in https://github.com/Pushtape/pushtape/issues/23#issuecomment-8896421 we have much more control with our own app. I will take the task upon myself to update and maintain. 

I'm not against being able to leverage an external app if we're able to brand and customize in code... but there currently is not such a solution.

**Comment by gusaus** [comment]
What happens if we just add back what was removed https://github.com/Pushtape/pushtape/commit/9949b94788a38411ed0671207130387d2c52944a

Would that circumvent this issue? https://github.com/Pushtape/pushtape/issues/32

**Comment by gusaus** [comment]
Per our discussion we've temporarily added this back to the makefile as referenced https://github.com/Pushtape/pushtape/issues/23#issuecomment-9055900

Great to have this working again. Thank you Luis!
