### ISSUE TITLE
Update platform on Aegir/Omega8.cc

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#24]
We currently have the following platforms set up on on Aegir - 

https://learn.ny.omega8.cc/hosting/c/platform_Pushtape7x1xpanels
https://learn.ny.omega8.cc/hosting/c/platform_PushtapePanels7x10alpha2

Assuming neither one is current we should select one to update and come up with a plan to maintain. Thoughts?

**Comment by discipolo** [comment]
Wait for next tag, its not worth upgrading to alpha3 in my eyes.

**Comment by discipolo** [comment]
you can now create a new platform with our alpha4 tag! https://raw.github.com/Pushtape/pushtape/4b42e12157ec5df0d50773fd2c2dc27b79b1ffbc/build-pushtape.make

**Comment by gusaus** [comment]
I made an attempt to set it up, but its throwing errors on install - 
https://learn.ny.omega8.cc/hosting/c/platform_PushtapePanels7x10alpha4

It's been awhile since I tried to set up a platform. Any ideas of what the problem is and/or can you get it running?

**Comment by discipolo** [comment]
you can see that the error aegir has is: "You can only specific branch or tag or revision but not combined in make file."

which i put down as https://github.com/Pushtape/pushtape/issues/4

**Comment by gusaus** [comment]
I see that error but am not clear on how to resolve.  What do we need to do?

**Comment by discipolo** [comment]
either panopoly change their code to be drush 4 compatible or https://learn.ny.omega8.cc updates its aegir ...

**Comment by discipolo** [comment]
it looks like omega8cc updated. just for you!
