### ISSUE TITLE
Create app or feature for home page

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#3]
Currently there is no landing page or panel for home. Should we create a feature or app for what we started to configure here?

http://dev.bandsite.gotpantheon.com/

Again we can probably use as a guide http://chapterthree.com/openacademy/

**Comment by discipolo** [comment]
thing is frontpage would have to depend on all features if it is supposed to display a pane for each...

**Comment by gusaus** [comment]
can we have the front page feature enabled by default (and have it set as the front page)?

**Comment by discipolo** [comment]
should be enabled by default
