### ISSUE TITLE
Apps still dont install fom appserver

### ISSUE THREAD

**Issue by discipolo** [Pushtape/pushtape#32]
Cannot extract zip or tar.gz files http://drupal.org/node/1551768

**Comment by discipolo** [comment]
possible but not ideal workaround: provide an archive somewhere else (not github) for the appserver.

**Comment by gusaus** [comment]
Ok - it's been quite awhile since this was logged. Do we know if this is still an issue? Also, is this what is throwing all these errors after the install apps screen? http://monosnap.com/image/1MLaIetKw5KuGOmXNSLdUU4T1

**Comment by discipolo** [comment]
a move to d.org seems the only solution... unless we figure out how to automatically upload our tags as zipfiles somewhere since none of us seem to be willing to do so manually the way nedjo did http://drupal.org/node/1571428#comment-6353320 or we figure out where in the apps module this can be remedied http://drupal.org/project/apps by overhauling the way the download url is handled in app.installer.inc

**Comment by gusaus** [comment]
I just asked to see if there was any progress http://drupal.org/node/1571428#comment-6796836

At this point, we'll just leave as is. Will push this back to the next milestone.

**Comment by gusaus** [comment]
this is working now i believe! if not, we'll reopen but shutting down for now!
