### ISSUE TITLE
panels branch on aegir fails 

### ISSUE THREAD

**Issue by discipolo** [Pushtape/pushtape#4]
http://drupal.org/node/1435156 this issue appears since we are including the panopoly make file which specifies revision and branch for contrib. i would like to keep this an include and not maintain our own version which would be the quick workaround to allow backward compatibility

issue is with drush 4.x. works fine with 5.x
aegir (and BOA on omega8cc) still run 4.x

**Comment by discipolo** [comment]
i put the workaround into place for now. so aegir install works now. just aditional work required to stay in sync with panopoly. so this is not resolved.

**Comment by discipolo** [comment]
workaround removed since drush 5.0 is now standard

**Comment by gusaus** [comment]
Per our discussion, this is still an issue that hopefully can be resolved somehow.

**Comment by discipolo** [comment]
install aegir-dev! it uses drush 5 (use aegir-up7.x-dev)so this issue is resolved!

**Comment by gusaus** [comment]
this has been resolved apparently
