### ISSUE TITLE
Invalid argument supplied for foreach() includes upon install

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#51]
Getting the following error when installing on pantheon.

CALL STACK
# Function    Location

1   drupal_alter(module_implements, Array ([dblog] => ), watchdog)  /includes/module.inc:719
2   drupal_alter()  /includes/module.inc:1027
3   watchdog(php, %type: !message in %function (line %line of %file)., Array ([%type] => Notice,[!message] => Undefined index: flux,[%function] => drupal_theme_initialize(),[%file] => /srv/bindings/b3004fe8fb5f4b2f9518601e72763a5d/code/includes/theme.inc,[%line] => 100,[severity_level] => 5), 5)    /includes/errors.inc:217
4   module_implements(watchdog)     /includes/bootstrap.inc:1764
5   _drupal_error_handler_real(8, Undefined index: flux, /srv/bindings/b3004fe8fb5f4b2f9518601e72763a5d/code/includes/theme.inc, 100, Array ([theme] => flux,[user] => stdClass Object ([uid] => 0,[hostname] => 98.246.155.35,[roles] => Array ([1] => anonymous user),[cache] => 0),[theme_key] => flux,[themes] => Array ([bartik] => stdClass Object ([filename] => themes/bartik/bartik.info,[name] => bartik,[type] => theme,[owner] => themes/engines/phptemplate/phptemplate.engine,[status] => 1,[bootstrap] => 0,[schema_version] => -1,[weight] => 0,[info] => Array ([name] => Bartik,[description] => A flexible, recolorable theme with many regions.,[package] => Core,[version] => 7.16,[core] => 7.x,[stylesheets] => Array ([all] => Array ([css/layout.css] => themes/bartik/css/layout.css,[css/style.css] => themes/bartik/css/style.css,[css/colors.css] => themes/bartik/css/colors.css),[print] => Array ([css/print.css] => themes/bartik/css/print.css)),[regions] => Array ([header] => Header,[help] => Help,[page_top] => Page top,[page_  /includes/bootstrap.inc:2266
6   _drupal_log_error(Array ([%type] => Notice,[!message] => Undefined index: flux,[%function] => drupal_theme_initialize(),[%file] => /srv/bindings/b3004fe8fb5f4b2f9518601e72763a5d/code/includes/theme.inc,[%line] => 100,[severity_level] => 5), )  /includes/errors.inc:90
7   drupal_theme_initialize()   /includes/common.inc:5062
8   _drupal_error_handler(8, Undefined index: flux, /srv/bindings/b3004fe8fb5f4b2f9518601e72763a5d/code/includes/theme.inc, 100, Array ([theme] => flux,[user] => stdClass Object ([uid] => 0,[hostname] => 98.246.155.35,[roles] => Array ([1] => anonymous user),[cache] => 0),[theme_key] => flux,[themes] => Array ([bartik] => stdClass Object ([filename] => themes/bartik/bartik.info,[name] => bartik,[type] => theme,[owner] => themes/engines/phptemplate/phptemplate.engine,[status] => 1,[bootstrap] => 0,[schema_version] => -1,[weight] => 0,[info] => Array ([name] => Bartik,[description] => A flexible, recolorable theme with many regions.,[package] => Core,[version] => 7.16,[core] => 7.x,[stylesheets] => Array ([all] => Array ([css/layout.css] => themes/bartik/css/layout.css,[css/style.css] => themes/bartik/css/style.css,[css/colors.css] => themes/bartik/css/colors.css),[print] => Array ([css/print.css] => themes/bartik/css/print.css)),[regions] => Array ([header] => Header,[help] => Help,[page_top] => Page top,[page_   /includes/theme.inc:100
9   drupal_bootstrap(7)     /index.php:20
10  _drupal_bootstrap_full()    /includes/bootstrap.inc:2226

**Comment by discipolo** [comment]
Invalid argument supplied for foreach() includes upon install
http://drupal.org/node/1417916
fixed in apps dev but panopoly core uses [apps][version] = 1.0-beta7 with
99 projects[apps][patch][1790902] = http://drupal.org/files/1790902-check-last-modified-existing.patch

this issue currently keeps my aegir site install from completing we need to ask panopoly people why they wont switch to apps beta (or if they have another workaround we can use) 

the error with  Undefined index: flux,[%function] => drupal_theme_initialize(),[%file] => /srv/bindings/b3004fe8fb5f4b2f9518601e72763a5d/code/includes/theme.inc,[ was a different issue taken care of with https://github.com/Pushtape/pushtape/commit/f1f169d8ed9cfad0a490e1714fa5085d504c7ae8

**Comment by gusaus** [comment]
this has been resolved!
