### ISSUE TITLE
Clean up install apps screen

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#58]
Currently the install apps screen looks like this - 

http://monosnap.com/image/v8R1Ro3I4U0RrBq2d02zV8RWC

How/where do we clean that up?

**Comment by discipolo** [comment]
pushtape.profile line 13 is where this app screen resides

**Comment by gusaus** [comment]
$tasks = $tasks + apps_profile_install_tasks($install_state, array('machine name' => 'panopoly', 'default apps' => array('pushtape_discography', 'pushtape_mediaplayer', 'pushtape_front'))

Above is line 13 but I don't see where the panopoly apps are or how to hide them. Any ideas?

**Comment by discipolo** [comment]
machine name is the machine name of the appserver. you can replace panopoly with pushtape there, which might hide panopoly apps. not sure what we want it to look like.

panopoly defines its appserver in panopoly.core.
we define our pushtape server in pushtape_u.module line 17.

also look at the last funtion in pushtape.profile function pushtape_form_apps_profile_apps_select_form_alter, here you can change the way the form looks

**Comment by gusaus** [comment]
Uhhh... easy for you to say! Lets try to work on this together when u can.

**Comment by gusaus** [comment]
So the install apps screen is pulling from http://apps.pushtape.openlearninglabs.org/? And if this issue is related https://github.com/Pushtape/pushtape/issues/32 we're currently not even using that server, right?

**Comment by gusaus** [comment]
Much better - http://monosnap.com/image/Ol7muwCrRq52ArjMGgoWHJWVe

Only thing now is to 1) remove mediagallery and 2) add pushtape_video and pushtape_photos

Would that be a huge hassle to do?

**Comment by discipolo** [comment]
thats a different issue
