### ISSUE TITLE
Check pushtape.install and verify its correct (or fix)

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#60]
I recently made some changes to work around new permissions changes that come /w Panopoly RC3. Most likely there is a better way to do. https://github.com/Pushtape/pushtape/commit/5d2b96a9ef4b5c98d8144be334ea40db75dcc6a4

**Comment by discipolo** [comment]
the commit you are referencing is removing the admin role. that just makes our code differ more from the barebones branch. apart from that it should be alright for now. i cannot think of any implications at the moment.

**Comment by gusaus** [comment]
In order for this branch to really leverage panopoly there will continue to be differences from pushtape on d.o. That said, we'll commit back as much as we can. Regarding this specific permissions issue, this d.o. issue is relevant to what we're doing and other distros that are incorporating panopoly. http://drupal.org/node/1737704 

Closing for now
