### ISSUE TITLE
install appmanifest module and update manifests on appserver

### ISSUE THREAD

**Issue by discipolo** [Pushtape/pushtape#67]
use it to export current manifest files and add .inc to our makefiles of all apps.
(tags are manually uploaded to appserver currently))

**Comment by gusaus** [comment]
its not exactly clear what to do, so i'm going to hold off on exporting all these apps. feel free to have at it if you're anxious!

**Comment by gusaus** [comment]
can you verify if this is done or not discipolo?

**Comment by discipolo** [comment]
right. i have updated the manifest files on the appserver. these are responsible for installing dependencies.
