### ISSUE TITLE
get basic functionality to work using minimal number of contrib modules

### ISSUE THREAD

**Issue by discipolo** [Pushtape/pushtape#68]
try to have as little dependencies as possible. especially our apps need to work independent of each other. (common stuff ins in pushtape_ui, which can be considered pushtape_core or pushtape_common or pushtape_base) even though that should also be discussed as a seperate issue. 
- pushtape_news should not depend on pushtape_front and not on media
- simplenews, follow, addthis and twitter should also not be part of the core features at this point.  we have enough weight. and this is what i think should be pushtape_connect
- which libraries do we really need?
  - colorbox?
  - flexslider 1.0
  - galleria 1.2.8
  - jquery.cycle 1.0
  - plupload 2.0a

can we discuss if and how to add all this in a following release? as far as the docs go they are not in the 1.0 release (and i propose some get their own apps)

pushtape-front should not depend on any other app either if possible (hard but possible)

**Comment by gusaus** [comment]
we have trimmed this down w/ future releases... still could do better
