### ISSUE TITLE
Add pushtape_video and pushtape_photos to the distro

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#69]
I'm not sure the process for adding to the appserver, but we already have alpha5 tags for each - 
https://github.com/Pushtape/pushtape_photos/tags
https://github.com/Pushtape/pushtape_video/tags

Can we get these added without too much trouble?

**Comment by discipolo** [comment]
i need the manifest files

**Comment by discipolo** [comment]
created initial appserver items
