### ISSUE TITLE
default_image in image_field_update_instance line 501 of image.module).

### ISSUE THREAD

**Issue by discipolo** [Pushtape/pushtape#7]
https://github.com/discipolo/pushtape/issues/6

http://drupal.org/node/1559696

add core patch? http://drupal.org/node/1559696

or something else? http://drupal.org/node/1558548

**Comment by gusaus** [comment]
Doing a fresh install now and it looks like the error is still hanging around - 
https://skitch.com/gusaus/ejdw9/pushtape-panels

**Comment by discipolo** [comment]
this is an issue of panopoly widgets (at least it surfaces when reverting that feature)

**Comment by gusaus** [comment]
Can not replicate on the latest release!
