### ISSUE TITLE
Remove extra branches

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#70]
Per our discussion lets remove the following branches for the time being - 
https://github.com/Pushtape/pushtape/tree/7.x-1.x-spark
https://github.com/Pushtape/pushtape/tree/7.x-1.x-upstream
https://github.com/Pushtape/pushtape/tree/8.x-1.x

We can add them back when there is a project/development need.

**Comment by discipolo** [comment]
we will rename upstream, remove spark and i will move 8.x to my personal repo. this does not have a high priority.

**Comment by gusaus** [comment]
Per zirafa we're going to shut down the lab.
