### ISSUE TITLE
find out how to Override apps version so that appserver can install libraries

### ISSUE THREAD

**Issue by discipolo** [Pushtape/pushtape#71]
player and soundmanager2 library made error. due to http://drupal.org/node/1348814
we need to ask panopoly people why they wont switch to apps dev (or if they have another workaround we can use to get the libraries to install)

**Comment by discipolo** [comment]
even overriding apps with dev verison i seem to get the same error and libraries dont install/download/unpack, can someone verify?

**Comment by discipolo** [comment]
overriding apps version in makefile didnt override, still downloaded beta version

**Comment by gusaus** [comment]
closing this down as we're 'currently' not using apps
