### ISSUE TITLE
check the timezone setting for recent changes that might cause this error

### ISSUE THREAD

**Issue by discipolo** [Pushtape/pushtape#74]
Notice: date_default_timezone_set(): Timezone ID '' is invalid in drupal_session_initialize() (line 273 of /var/aegir/platforms/pushtape-panels-alpha6/includes/session.inc).
Notice: date_default_timezone_set(): Timezone ID '' is invalid in drupal_session_regenerate() (line 412 of /var/aegir/platforms/pushtape-panels-alpha6/includes/session.inc).

**Comment by gusaus** [comment]
can't replicate at the moment
