### ISSUE TITLE
Associate track 'label' field with artist.

### ISSUE THREAD

**Issue by gusaus** [Pushtape/pushtape#94]
As is the case with track artwork, release date, and artist... the 'label' field needs to pick up the 'album' label if left blank.

![image](https://f.cloud.github.com/assets/113996/520932/94e72b10-bf54-11e2-80ee-ef1ad6535680.png)

**Comment by discipolo** [comment]
how about a corresponding feature request http://drupal.org/project/issues/pushtape?status=All&categories=All here since this cannot be solve via a recipe

**Comment by gusaus** [comment]
This is the related feature request on d.o. http://drupal.org/node/1878262. On this particular branch we just need to get the functionality to work.

**Comment by gusaus** [comment]
This has since been resolved
